### ISSUE TITLE
EOFError with Gzip read

### ISSUE THREAD

**Issue by mccarthyryanc** [dask/s3fs#225]
I created an [issue](https://github.com/pandas-dev/pandas/issues/28206) on the Pandas repo, but it looks like it might be an s3fs, versions 0.3.0 and greater, error.

```python
import pandas as pd
data = pd.read_csv("s3://bucketname/file.csv.gz")
```

Gives the following error:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ubuntu/miniconda3/envs/test/lib/python3.7/site-packages/pandas/io/parsers.py", line 685, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/ubuntu/miniconda3/envs/test/lib/python3.7/site-packages/pandas/io/parsers.py", line 463, in _read
    data = parser.read(nrows)
  File "/home/ubuntu/miniconda3/envs/test/lib/python3.7/site-packages/pandas/io/parsers.py", line 1154, in read
    ret = self._engine.read(nrows)
  File "/home/ubuntu/miniconda3/envs/test/lib/python3.7/site-packages/pandas/io/parsers.py", line 2059, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 881, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 896, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 950, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 937, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 2124, in pandas._libs.parsers.raise_parser_error
  File "/home/ubuntu/miniconda3/envs/test/lib/python3.7/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/home/ubuntu/miniconda3/envs/test/lib/python3.7/gzip.py", line 482, in read
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached
```

### Setup
Installed Pandas and s3fs via pip:
```bash
pip install pandas s3fs
```
**Pandas version:** 0.25.1
**s3fs version:** 0.3.3

**Comment by mccarthyryanc** [comment]
Looks like the problem is unrelated to pandas:
```python
import gzip
import s3fs
fs = s3fs.S3FileSystem()
s3_fh = fs.open('s3://bucketname/file.csv.gz')
fh = gzip.open(s3_fh)
data = fh.read()
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/miniconda3/envs/test/lib/python3.7/gzip.py", line 276, in read
    return self._buffer.read(size)
  File "/home/ubuntu/miniconda3/envs/test/lib/python3.7/gzip.py", line 482, in read
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached
```
Again, the s3fs+gzip read works in versions < 0.3.0.

**Comment by Jflick58** [comment]
Weird timing,  but I am experiencing the same issue with s3fs==0.3.3.  Files that previously work on 0.2.0 now fail with EOFError

**Comment by meneal** [comment]
I am hitting the same error with `s3fs==0.3.3` on gzipped files.

**Comment by meneal** [comment]
Since s3fs hasn't been released in almost a month, I think this is due to one of the three dependencies pushing a break change. I tested boto3's latest version and botocores latest version and had no problem accessing gzipped files so I would think that clears both boto3 and botocore.

It looks to me that `filesystem_spec` pushed some code yesterday  in [this commit](https://github.com/intake/filesystem_spec/commit/7d6d80d6f7b500a5a4d69766e52c641018f613b8) and [this commit](https://github.com/intake/filesystem_spec/commit/6f69ea2162d442d2654edd4f9739ba8114d78fb3)  in two releases that may be the culprit. I don't know this space quite well enough to be able to debug their work, but I hope this might help in some heuristic sense.

**Comment by meneal** [comment]
After another quick check, I can confirm that downgrading by using:

`pip install fsspec==0.4.1`

and pulling files using s3fs works fine.

**Comment by TomAugspurger** [comment]
Thanks for the report. Taking a look.

**Comment by TomAugspurger** [comment]
I'm able to reproduce, but only on a real request against s3, not with moto. I'll look into this today though, and should be able to do a release of fsspec once it's fixed.

**Comment by shawnzhu** [comment]
I tried `fsspec==0.4.3` still got the same error as that from https://github.com/dask/s3fs/issues/225#issue-486662802

So while pending on a fix from `fsspec`, May I ask for a minor release to include :point_up: workaround so `s3fs` users like me won't need to dig into this issue to find a workaround?

**Comment by TomAugspurger** [comment]
I think you need fsspec==0.4.1

**Comment by shawnzhu** [comment]
> I think you need `fsspec==0.4.1`

Yes, that's what I tried to apply via #226

**Comment by TomAugspurger** [comment]
Well that was a fun diversion. I've kinda figured out why we couldn't reproduce with moto.

When we get to the end of the file, we make a request to S3 with byte range request like `range=3-2`. According to https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.35, that's invalid

> If the last-byte-pos value is present, it MUST be greater than or equal to the first-byte-pos in that byte-range-spec, or the byte- range-spec is syntactically invalid. The recipient of a byte-range- set that includes one or more syntactically invalid byte-range-spec values MUST ignore the header field that includes that byte-range- set.

So IIUC, the server is suppose to ignore that header and return the full body. S3 does indeed do that. Moto (which I think uses httpretty) doesn't. Instead, there's an InvalidRangeRequest exception, which s3fs catches.

**Comment by TomAugspurger** [comment]
This *should* be fixed with #229. If anyone wants to test that out quickly, I'd appreciate it, since we can't actually write a unit test for this (that doesn't hit S3). But with my local testing, things are OK.

Otherwise, I'll do a release later this afternoon.

**Comment by shawnzhu** [comment]
I can confirm code in master (v0.3.4) branch works for me w/ `fsspec==0.4.3`.

@TomAugspurger Thanks! when we can see this from `pypi.org`? the latest release over there still shows `0.3.3` (Aug 8, 2019).

**Comment by mccarthyryanc** [comment]
@TomAugspurger works for me! Thanks for the quick work on getting a fix!

**Comment by TomAugspurger** [comment]
0.3.4 is on PyPI. Will show up on Conda-forge later today.

**Comment by shawnzhu** [comment]
@TomAugspurger Thanks for quick fix and release!
