### ISSUE TITLE
AttributeError: 'module' object has no attribute 'ReadTimeoutError'

### ISSUE THREAD

**Issue by rolando** [dask/s3fs#63]
Latest release of `boto3` breaks `s3fs`.

Meanwhile this gets a proper fix, this PR pins `boto3` version; https://github.com/dask/s3fs/pull/62

**Comment by EdwinRor** [comment]
How did you fix it? What versions do i need to get it to work?

**Comment by mrocklin** [comment]
This is fixed in master

    pip install git+https://github.com/dask/s3fs --upgrade

**Comment by EdwinRor** [comment]
Sorry, i think i had done this earlier and now but the problem still persists

**Comment by mrocklin** [comment]
Can you provide an repeatable example that produces the exception that you're getting?

**Comment by EdwinRor** [comment]
edwin@edwin-Lenovo-FLEX-3-1130 ~ $ python2
Python 2.7.12 (default, Jul  1 2016, 15:12:24) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import s3fs
>>> 
#This works
#############################################
edwin@edwin-Lenovo-FLEX-3-1130 ~ $ python3
Python 3.5.2 (default, Jul  5 2016, 12:43:10) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import s3fs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/s3fs/__init__.py", line 1, in <module>
    from .core import S3FileSystem, S3File
  File "/usr/local/lib/python3.5/dist-packages/s3fs/core.py", line 23, in <module>
    trans.ReadTimeoutError, trans.IncompleteReadError
AttributeError: module 'boto3.s3.transfer' has no attribute 'ReadTimeoutError'
>>>

**Comment by EdwinRor** [comment]
edwin@edwin-Lenovo-FLEX-3-1130 ~ $ python2
Python 2.7.12 (default, Jul  1 2016, 15:12:24) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import s3fs
>>> 
#This works
#############################################
edwin@edwin-Lenovo-FLEX-3-1130 ~ $ python3
Python 3.5.2 (default, Jul  5 2016, 12:43:10) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import s3fs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/s3fs/__init__.py", line 1, in <module>
    from .core import S3FileSystem, S3File
  File "/usr/local/lib/python3.5/dist-packages/s3fs/core.py", line 23, in <module>
    trans.ReadTimeoutError, trans.IncompleteReadError
AttributeError: module 'boto3.s3.transfer' has no attribute 'ReadTimeoutError'
>>>

**Comment by EdwinRor** [comment]
edwin@edwin-Lenovo-FLEX-3-1130 ~ $ python2
Python 2.7.12 (default, Jul  1 2016, 15:12:24) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import s3fs
>>> 
#This works
#############################################
edwin@edwin-Lenovo-FLEX-3-1130 ~ $ python3
Python 3.5.2 (default, Jul  5 2016, 12:43:10) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import s3fs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/s3fs/__init__.py", line 1, in <module>
    from .core import S3FileSystem, S3File
  File "/usr/local/lib/python3.5/dist-packages/s3fs/core.py", line 23, in <module>
    trans.ReadTimeoutError, trans.IncompleteReadError
AttributeError: module 'boto3.s3.transfer' has no attribute 'ReadTimeoutError'
>>>

**Comment by mrocklin** [comment]
Can you verify that the following fails:

```
pip3 install git+https://github.com/dask/s3fs.git --upgrade
python3
import s3fs
```

**Comment by EdwinRor** [comment]
The problem still persists.

HERE IS MY TEMPORARY FIX TILL YOU GET A GOOD FIX:
change line 24 in core.py to:
S3_RETRYABLE_ERRORS = (boto3.compat.SOCKET_ERROR,)
because,
"socket.timeout" is not an attribute of boto3.s3.transfer

**Comment by mrocklin** [comment]
I'm not sure what you mean by this:

> "socket.timeout" is not an attribute of boto3.s3.transfer

`socket.timeout` is part of the standard library:

```python
In [1]: import socket

In [2]: socket.timeout
Out[2]: socket.timeout
```

**Comment by EdwinRor** [comment]
In that case line 23 & 24 of core.py should be:

except ImportError:
    socket.timeout

instead of:

except ImportError:
    S3_RETRYABLE_ERRORS = (
        socket.timeout,
)

**Comment by mrocklin** [comment]
What would the value of `S3_RETRYABLE_ERRORS` be in that case?

**Comment by EdwinRor** [comment]
Never mind. 
So far i know i am using the wrong boto3 module or branch that produces that error.
 I will start over again.

**Comment by EdwinRor** [comment]
You can go ahead and close it. Thanks.

**Comment by EdwinRor** [comment]
After messing around with the different branches of boto3 and to answer your question, S3_RETRYABLE_ERRORS is a hit or misss import from boto3.s3.transfer.
I think the right fix should be:
 `try:
    from boto3.s3.transfer import S3_RETRYABLE_ERRORS
except ImportError:
    S3_RETRYABLE_ERRORS = None
`
I have tested this and it works.

**Comment by mrocklin** [comment]
Sometimes we *do* want to retry when we hit a retryable error.  If you look further down in the code you'll find that this is used within an `except S3_RETRYABLE_ERRORS` clause.  So this needs to be a tuple of exceptions on which we are comfortable retrying.

**Comment by EdwinRor** [comment]
In that  case we need to recreate the complete tuple
 or use the simplified tuple of None
`
import socket
import boto3
from botocore.vendored.requests.packages.urllib3.exceptions import ReadTimeoutError
from botocore.exceptions import IncompleteReadError

S3_RETRYABLE_ERRORS = (
    socket.timeout, boto3.compat.SOCKET_ERROR,
    ReadTimeoutError, IncompleteReadError
)

or 

S3_RETRYABLE_ERRORS = (None,)
`

Regards.

**Comment by rolando** [comment]
@EdwinRor Could you share the output of the following command?

`python -c "import boto3; print(boto3.__version__)"`

**Comment by EdwinRor** [comment]
1.4.0
s3fs pulls the latest version of boto3 all the time unless you install it first.

**Comment by martindurant** [comment]
Fixed in #62
