### ISSUE TITLE
v4 authentication issue

### ISSUE THREAD

**Issue by katsou55** [dask/s3fs#88]
import s3fs
    from fastparquet import ParquetFile
    from fastparquet import write
    
    s3 = s3fs.core.S3FileSystem(key=GLOBAL_ACCESS_KEY, 
                  secret=GLOBAL_SECRET_KEY)
                    #,client_kwargs={'config': Config(signature_version="s3v4")})
    
    myopen = s3.open
```
noop = lambda x: True
write('marionte-test/temp_parq', df, file_scheme='hive', open_with=myopen, mkdirs=noop,     compression='SNAPPY')
```

Error:

    IOError                                   Traceback (most recent call last)
    <ipython-input-91-7e826066cd11> in <module>()
    ----> 1 write('marionte-test/temp_parq', df, file_scheme='hive', open_with=myopen, mkdirs=noop, compression='SNAPPY')
    
    /Users/carlosrodrigues/anaconda/envs/testenv/lib/python2.7/site-packages/fastparquet/writer.pyc in write(filename, data, row_group_offsets, compression, file_scheme, open_with, mkdirs, has_nulls, write_index, partition_on, fixed_text, append, object_encoding, times)
        779                 with open_with(partname, 'wb') as f2:
        780                     rg = make_part_file(f2, data[start:end], fmd.schema,
    --> 781                                         compression=compression)
        782                 for chunk in rg.columns:
        783                     chunk.file_path = part
    
    /Users/carlosrodrigues/anaconda/envs/testenv/lib/python2.7/site-packages/s3fs/core.pyc in __exit__(self, *args)
       1143 
       1144     def __exit__(self, *args):
    -> 1145         self.close()
       1146 
       1147 
    
    /Users/carlosrodrigues/anaconda/envs/testenv/lib/python2.7/site-packages/s3fs/core.pyc in close(self)
       1115                                           Body=self.buffer.read(), ACL=self.acl)
       1116                 except (ClientError, ParamValidationError) as e:
    -> 1117                     raise IOError('Write failed: %s' % self.path, e)
       1118             self.s3.invalidate_cache(self.path)
       1119         self.closed = True
    
    IOError: [Errno Write failed: marionte-test/temp_parq/part.0.parquet] An error occurred (InvalidRequest) when calling the PutObject operation: The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.

Usually in boto3 client I would solve it by passing the region or the signature_version.
s3fs documentation refer about -> config_kwargs : dict of parameters passed to botocore.client.Config as an argument in S3FileSystem which would be useful to solve this problem
http://s3fs.readthedocs.io/en/latest/api.html

However the argument is not present, I tried to use client_kwargs however it does not let me pass my own conf...
Any suggestion so solve this?

**Comment by martindurant** [comment]
Of the many places to which parameters are passed, the client Config is not one of them. You could maybe try the following:
```
s3.s3.meta.config.signature_version = "s3v4"
```

Happy to try to find a way to pass keyword arguments to the client, session and config, or provide an alternate mechanism for evaluating boto parameters.

**Comment by martindurant** [comment]
Are you using the latest master version? This should have been solved in #86

**Comment by katsou55** [comment]
Yes, it works! I was able to setup the signature and also the region! Thanks!
(We can close this issue)

However I am not yet able to write into s3. I still have the same error.

**Comment by martindurant** [comment]
Hm, interesting. Writing uses the very same underlying boto client as reading, odd that one should give you the error but not the other (unless, of course, you lack correct permissions).

**Comment by katsou55** [comment]
(I mean, I used your suggestion and it worked well. Also I already pulled the code from master and I got the config_kwargs which worked.)

Agree,  lack of correct permissions is a very good possibility (not the first time it)! The odd is that I am creating buckets, putting data into s3 with boto3 client with those same keys.

Anyway thx for help. This packages dask is working on are very useful.

**Comment by katsou55** [comment]
Well, now is working by magic. (After restarting sometimes jupyter)
